import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <script
          async
          defer
          src="https://apis.google.com/js/api.js"
          onLoad={()=>gapiLoaded()}
        />
        <script
          async
          defer
          src="https://accounts.google.com/gsi/client"
          onLoad={()=>gisLoaded()}
        />
        </Head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
